

---
title: "Now we tell about fishing."
date: 2018-08-22
---







title: Now we tell about fishing.      
author: Drogg
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Dialogies about fishing. Where we fishing.
  What hooks we use and about some secrets in baits!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima



